### ISSUE TITLE
Somehow it is not working

### ISSUE THREAD

**Issue by cherltte** [kennethlimcp/spark-LSM9DS0#1]
Hi there

I am trying to connect LSM9DS0 with spark core.
Somehow it is not working.
I used exactly the same code that you have provided. I could upload the library and one of example code. but I cannot get any communication with the device at all. 
it seems the program is in infinite loop or something (the core is cyan breathing but it is not access-able state). So I need to factory reset and re-setup. 

I wire SCL to A3
SDA to D0

I am pretty newbie in this, hope someone can help me.

thanks

rcp

**Comment by kennethlimcp** [comment]
Do you have pull-up resistors on the I2C line?

**Comment by cherltte** [comment]
Thanks for you reply Kennethlimcp
It is working now. I don't have pull-up resistors though. 
I removed 'while' statement in the coding. Somehow it starts working.
what does while do? sorry for beginner's question.

**Comment by kennethlimcp** [comment]
which example are you using and which `while()` statement did you remove?

If you did not use the pull-up resistors, i don't think your device will function properly

**Comment by cherltte** [comment]
Hi Kennethlimcp,

Sorry for late reply. I did try as your advice and it worked! Thanks.
But now I am confronting another issue.
I am trying to monitor activities of Particle Core. I set up a web page to track the mode of the particle core using setInterval javascript and Particle Core variable. I used a button switch to switch modes. This works just fine without LSM Sensor. However, when I add library with the function call motionDetection, Particle Core goes to infinite loop (where led indicates breathing cyan, but inaccessible). Here is my code

// This #include statement was automatically added by the Spark IDE.
#include "Adafruit_Sensor.h"

// This #include statement was automatically added by the Spark IDE.
#include "Adafruit_LSM9DS0.h"

/* Assign a unique base ID for this sensor */
Adafruit_LSM9DS0 lsm = Adafruit_LSM9DS0(12345);  // Use I2C, ID #1000

float motionXaxis = 0.0;
float pre_motionXaxis = 0.0;

int button = D2;
int storyMode =0;

int led = D7;
int led2 = D6;
int curState = 0;
int preState = 0;

int movementDetected = 0;
String sendingMode;


void setup()
{
  Serial.begin(9600);


   if(!lsm.begin())
   {
     Serial.print(F("Ooops, no LSM9DS0 detected ... Check your wiring or I2C ADDR!"));
     while(1);
   }
   Serial.println(F("Found LSM9DS0 9DOF"));

  configureSensor();
  //Spark.subscribe("movement", motionDetection); //receiving data from T2
  Spark.variable("getStory", &storyMode, INT); //informing data
  Spark.function("setStory", setStoryWeb);
  pinMode(button, INPUT);
  pinMode(led, OUTPUT);
  pinMode(led2, OUTPUT);

}

void configureSensor()
{
  // 1.) Set the accelerometer range
  lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_2G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_4G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_6G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_8G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_16G);

  // 2.) Set the magnetometer sensitivity
  lsm.setupMag(lsm.LSM9DS0_MAGGAIN_2GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_4GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_8GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_12GAUSS);

  // 3.) Setup the gyroscope
  lsm.setupGyro(lsm.LSM9DS0_GYROSCALE_245DPS);
  //lsm.setupGyro(lsm.LSM9DS0_GYROSCALE_500DPS);
  //lsm.setupGyro(lsm.LSM9DS0_GYROSCALE_2000DPS);
}
void loop()
{
  buttonInput();
  motionDetection();
}

void buttonInput(){
  curState = digitalRead(button);
  if(curState != preState){
    if(curState == HIGH){
      changeStoryMode();
    }
  }
  preState = curState;
}

int setStoryWeb(String storyValue){
  int newValue = storyValue.toInt();
  if(newValue == 1){
    storyMode = 2;
    changeStoryMode();
  }
  else if(newValue == 2){
    storyMode = 1;
    changeStoryMode();

  } else {
    storyMode = 99;
  }
  return 0;
}

void changeStoryMode(){

  if(storyMode == 0){
    storyMode = 1;
    sendingMode = "1";
  }
  else if(storyMode == 1){
    storyMode = 2;
    sendingMode = "2";
  }
  else if(storyMode == 2){
    storyMode = 1;
    sendingMode = "1";
  }
  else {
    storyMode = 99;
    sendingMode = "99";
  }

  Serial.println(storyMode);
  Spark.publish("storyMode", sendingMode);
}


void motionDetection(){
  sensors_event_t accel, mag, gyro, temp;

  lsm.getEvent(&accel, &mag, &gyro, &temp);

  /*// print out accelleration data
  Serial.print("Accel X: "); Serial.print(accel.acceleration.x); Serial.print(" ");
  Serial.print("  \tY: "); Serial.print(accel.acceleration.y);       Serial.print(" ");
  Serial.print("  \tZ: "); Serial.print(accel.acceleration.z);     Serial.println("  \tm/s^2");

  // print out magnetometer data
  Serial.print("Magn. X: "); Serial.print(mag.magnetic.x); Serial.print(" ");
  Serial.print("  \tY: "); Serial.print(mag.magnetic.y);       Serial.print(" ");
  Serial.print("  \tZ: "); Serial.print(mag.magnetic.z);     Serial.println("  \tgauss");

  // print out gyroscopic data
  Serial.print("Gyro  X: "); Serial.print(gyro.gyro.x); Serial.print(" ");
  Serial.print("  \tY: "); Serial.print(gyro.gyro.y);       Serial.print(" ");
  Serial.print("  \tZ: "); Serial.print(gyro.gyro.z);     Serial.println("  \tdps");

  // print out temperature data
  Serial.print("Temp: "); Serial.print(temp.temperature); Serial.println(" *C");

  Serial.println("**********************\n");*/

  motionXaxis = gyro.gyro.x;
  Serial.println(motionXaxis);
  delay(20);
  if(abs(pre_motionXaxis - motionXaxis) > 150){
    digitalWrite(led, HIGH);

  }
  else{
    digitalWrite(led, LOW);
  }
  pre_motionXaxis = motionXaxis;
}

Please help me. 

Thanks in advance.

**Comment by kennethlimcp** [comment]
@cherltte, i think you are performing too many `Spark.publish()` every second which might be causing the issue.

**Comment by cherltte** [comment]
@kennethlimcp hey, thanks for the quick response!
So gyro sensor conflicts with Spark.publish(). Hm, I didn't have this problem without the sensor. One thing that doesn't make sense to me is that I intended to publish only when the button is clicked.

**Comment by kennethlimcp** [comment]
Does this example work well? https://github.com/kennethlimcp/spark-LSM9DS0/blob/master/firmware/examples/lsm9doftest.ino

**Comment by cherltte** [comment]
this example works well. data value seems bigger than previous one though.

**Comment by kennethlimcp** [comment]
Maybe you can work from the example code and continue from there. If you still have issues, feel free to open a thread at https://community.particle.io

**Comment by cherltte** [comment]
I am still having the same problem, but Thanks for your help! I will post this issue.
